(()=>{"use strict";const $=s=>document.querySelector(s);
const timeout=(ms=9000)=>new Promise((_,rej)=>setTimeout(()=>rej(new Error("Request timeout")),ms));
async function getJSON(url,options={}){const r=await Promise.race([fetch(url,options),timeout()]);if(!r.ok)throw new Error("HTTP "+r.status);const d=await r.json();if(d===null||d===undefined)throw new Error("Invalid JSON");return d}
function raw(id,d){$(id).textContent=JSON.stringify(d,null,2).slice(0,6000)}
function status(id,ok){const e=$(id);e.textContent=ok?"● API ONLINE":"● API ERROR";e.classList.toggle("bad",!ok)}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function clock(){const n=new Date();$("#clock").textContent=n.toLocaleTimeString([],{hour:"2-digit",minute:"2-digit",second:"2-digit"});$("#year").textContent=n.getFullYear()}clock();setInterval(clock,1000);
const codes={0:["☀","Clear"],1:["🌤","Mainly clear"],2:["⛅","Partly cloudy"],3:["☁","Overcast"],45:["🌫","Fog"],48:["🌫","Fog"],51:["🌦","Drizzle"],53:["🌦","Drizzle"],55:["🌧","Drizzle"],61:["🌦","Rain"],63:["🌧","Rain"],65:["🌧","Heavy rain"],71:["🌨","Snow"],73:["❄","Snow"],75:["❄","Heavy snow"],80:["🌦","Showers"],81:["🌧","Showers"],82:["⛈","Heavy showers"],95:["⛈","Thunderstorm"],96:["⛈","Thunderstorm"],99:["⛈","Thunderstorm"]};
async function weather(lat=29.9038,lon=73.8772,label="Sri Ganganagar, IN"){try{const u=`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,weather_code,wind_speed_10m&timezone=auto`;const d=await getJSON(u);const [i,desc]=codes[d.current.weather_code]||["☁","Current"];$("#weather").textContent=`${Math.round(d.current.temperature_2m)}°C · ${desc}`;$("#place").textContent=label;$("#wicon").textContent=i;$("#temp").textContent=Math.round(d.current.temperature_2m)+"°C";$("#wdesc").textContent=desc;$("#wmeta").textContent=`Wind ${Math.round(d.current.wind_speed_10m)} km/h · ${d.timezone}`;raw("#weatherRaw",d);status("#weatherStatus",true)}catch(e){$("#weather").textContent="Weather unavailable";$("#place").textContent=e.message;status("#weatherStatus",false);raw("#weatherRaw",{error:e.message})}}
$("#weatherBtn").onclick=()=>weather();if(navigator.geolocation)navigator.geolocation.getCurrentPosition(p=>weather(p.coords.latitude,p.coords.longitude,"Your location"),()=>weather());else weather();
async function github(){try{const d=await getJSON("https://api.github.com/users/pkdiv6548");$("#githubResult").innerHTML=`<strong>${esc(d.name||d.login)}</strong><span>${esc(d.bio||"Public GitHub profile")}</span><br><a href="${esc(d.html_url)}" target="_blank" rel="noopener">Open GitHub ↗</a><br><small>${d.public_repos} public repos · ${d.followers} followers</small>`;raw("#githubRaw",d);status("#githubStatus",true)}catch(e){error("#githubResult",e);status("#githubStatus",false);raw("#githubRaw",{error:e.message})}}
function error(id,e){$(id).innerHTML=`<span style="color:#ff7d7d">Request failed: ${esc(e.message)}</span>`}
$("#githubBtn").onclick=github;github();
async function news(){try{const ids=await getJSON("https://hacker-news.firebaseio.com/v0/topstories.json");const rows=await Promise.all(ids.slice(0,5).map(id=>getJSON(`https://hacker-news.firebaseio.com/v0/item/${id}.json`)));$("#newsResult").innerHTML=rows.map(x=>`<div style="margin-bottom:10px"><a href="${esc(x.url||"#")}" target="_blank" rel="noopener">${esc(x.title||"Untitled")} ↗</a><small style="display:block;color:#666">${x.score||0} points · ${x.descendants||0} comments</small></div>`).join("");raw("#newsRaw",rows);status("#newsStatus",true)}catch(e){error("#newsResult",e);status("#newsStatus",false);raw("#newsRaw",{error:e.message})}}$("#newsBtn").onclick=news;news();
async function books(){try{const q=["javascript","web design","artificial intelligence","css"][Math.floor(Math.random()*4)];const d=await getJSON(`https://openlibrary.org/search.json?q=${encodeURIComponent(q)}&limit=3`);const b=d.docs?.[0];$("#bookResult").innerHTML=`<strong>${esc(b?.title||"No result")}</strong><span>${esc(b?.author_name?.[0]||"Unknown")} · ${b?.first_publish_year||"—"}</span><small>Query: ${esc(q)} · ${d.numFound||0} results</small>`;raw("#bookRaw",{query:q,numFound:d.numFound,docs:d.docs});status("#bookStatus",true)}catch(e){error("#bookResult",e);status("#bookStatus",false);raw("#bookRaw",{error:e.message})}}$("#bookBtn").onclick=books;books();
async function user(){try{const d=await getJSON("https://randomuser.me/api/?nat=in");const u=d.results?.[0];$("#userResult").innerHTML=`<img src="${esc(u.picture.medium)}" alt=""><strong>${esc(u.name.first+" "+u.name.last)}</strong><span>${esc(u.email)}</span><small>${esc(u.location.city)}, ${esc(u.location.country)}</small><div style="clear:both"></div>`;raw("#userRaw",u);status("#userStatus",true)}catch(e){error("#userResult",e);status("#userStatus",false);raw("#userRaw",{error:e.message})}}$("#userBtn").onclick=user;user();
async function joke(){try{const d=await getJSON("https://v2.jokeapi.dev/joke/Any?safe-mode");const t=d.type==="single"?d.joke:`${d.setup}\n${d.delivery}`;$("#jokeResult").innerHTML=`<strong>“${esc(t)}”</strong>`;raw("#jokeRaw",d);status("#jokeStatus",true)}catch(e){error("#jokeResult",e);status("#jokeStatus",false);raw("#jokeRaw",{error:e.message})}}$("#jokeBtn").onclick=joke;joke();
$("#theme").onclick=()=>{document.body.classList.toggle("light");localStorage.setItem("theme",document.body.classList.contains("light")?"light":"dark")};if(localStorage.getItem("theme")==="light")document.body.classList.add("light");
})();